name: Run main.py with Cloud SQL Proxy

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Start Cloud SQL Proxy
      uses: google-github-actions/setup-cloud-sql-proxy@v1
      with:
        instance_connection_name: 'boreal-atom-450721-q8:europe-west1:dashboard-for-streaming-data'
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        port: 5432

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DATABASE_URL: postgresql+psycopg2://youruser:yourpassword@127.0.0.1:5432/your_db_name
      run: python main.py
